### ISSUE TITLE
Implement workers

### ISSUE THREAD

**Issue by jakejack13** [jakejack13/SPEED#1]
### Summary
To begin the project, we will first create the worker node. Worker nodes are tasked with cloning the repository they will be operating on, building the targets needed for running tests, and running those tests. 

### Specification
Inputs: URL of git repo, branch, list of tests to run
Output: Results of tests

### Things to Consider
- How should tests be outputted? Printed to stdout? File created with summary?
- FUTURE: Will the workers be connected to the leader via a socket to provide live updates on execution of tests?

### TODO
- [x] Create repository cloning mechanism
- [x] Create project building mechanism
- [x] Run tests with JUnit runner
- [x] Output results
- [x] Create Docker image for easy execution
