### ISSUE TITLE
Create worker Docker container deployer and executor

### ISSUE THREAD

**Issue by jakejack13** [jakejack13/SPEED#15]
### Summary
We need to create a system that creates Docker containers from the worker Docker image, starts the container with the necessary environment variables for the worker to function, and waits for the container to finish executing before freeing up resources.

### Tasks
- [ ] Allocate resources ( `docker create` ) for a given number of Docker containers
- [ ] Assign specific tests to each container and execute ( `docker start` )
- [ ] Check if container is finished executing
- [ ] Wait for container to finish, report result, and clean up resources ( `docker rm` )

**Comment by owenxr** [comment]
Currently Kafka Output Stream is not showing test results.
