### ISSUE TITLE
Allow Configuration File (and subsequent systems) to Parse and Load from Multiple Build Directories

### ISSUE THREAD

**Issue by owenxr** [jakejack13/SPEED#16]
### Summary

The current class loading system makes the assumption that rendered `.class` files are in the directory `build/classes/java` relative to the root project directory. We want to not only want to remove the hardcoded aspect of looking for `.class` files, but also improve customization by specifically selecting where to load from. The configuration file should then handle multiple build directories, which should be read by our repository and then passed into the loader as such. 

### Tasks

- [ ] Add and Parse multiple build directories into list from config file
- [ ] Pass it through to the worker
- [ ] Worker then uses it to load appropriate directories and subdirectories
