### ISSUE TITLE
[First] Dockerize leaders

### ISSUE THREAD

**Issue by jakejack13** [jakejack13/SPEED#24]
### Summary
The leader should now but run from within a docker container while retaining the same functionality.

### TODO:
- [x] Implement system to spin up leader as a docker container 
- [x] Ensure it works with the current system
- [x] Spin the system up either using a script or CLI command or easy runnable
