### ISSUE TITLE
[First] Create result sharing functionality

### ISSUE THREAD

**Issue by jakejack13** [jakejack13/SPEED#29]
### Summary

After the results database is created, we need a way for leaders to communicate their results to first and a way for the web server to store these results and share this information with users. 

### TODO
- [x] Add a new env variable to leaders to share the URL of first
- [x] Create JSONifier from leader to first 
- [x] Add new result sharing system to leaders to share results with first via API
