### ISSUE TITLE
[Optimizer] Create boilerplate project structure

### ISSUE THREAD

**Issue by jakejack13** [jakejack13/SPEED#43]
### Summary
To start off the creation of the optimizer service, we need to create the base files of the Flask app. 

### TODO
- [ ] Create new Flask project in `microservices/optimizer`
- [ ] Create `main.py` with prototypes for endpoints
- [ ] Create `utils/db_manager.py` with database management function prototypes
- [ ] Create `utils/optimizer.py` with optimizer management function prototypes
